@startuml
'https://plantuml.com/class-diagram

'Styling
skinparam linetype polyline


'================
'==== JMdict ====
'================
package jmdict {
    class Entry {
        long id
        long entSeq
    }

    class Kanji {
        long id
        Entry entry
        String kanji
        Set<String> orthographyInformation
        Set<String> priorityInformation
    }

    class Reading {
        long id
        Entry entry
        String element
        boolean nokanji
        Set<String> readingInformation
        Set<String> priorityInformation
        Set<String> alternativeReadings
    }

    class Sense {
        long id
        Entry entry
        Set<String> limitedToKanji
        Set<String> limitedToReadings
        Set<String> partOfSpeech
        Set<String> crossReferences
        Set<String> antonyms
        Set<String> fieldsOfApplication
        Set<String> miscellaneousInformation
        Set<String> senseInformation
        Set<LoanwordSource> loanwordSources
        Set<String> dialects
        Set<Gloss> glosses
    }

    class LoanwordSource {
        long id
        Sense sense
        String element
        String languageCode
        String semanticCoverage
        String isConstructedFromSourceLanguageWord
    }

    class Gloss {
        long id
        Sense sense
        String languageCode
        String gender
        String semanticProperty
    }

    'Relationships
    Entry <-down- Kanji
    Entry <-down- Reading
    Entry <-down- Sense

    Sense <-down- LoanwordSource
    Sense <-down- Gloss
}


'=================
'=== Kanjidic2 ===
'=================
package kanjidic2 {
    class Character {
        long id
        String literal
        int frequency
        int schoolGrade
        int jlptGrade
        int strokeCount
        Set<Variant> variants
        Set<String> radicalNames
        Set<Codepoint> codepoints
        Set<Radical> radicals
        Set<DictionaryReference> references
        Set<QueryCode> queryCodes
        Set<RMGroup rmgroups
        Set<String> nanori
    }

    class Codepoint {
        long id
        Character character
        String type
        String value
    }

    class Radical {
        long id
        Character character
        String type
        String value
    }

    class Variant {
        long id
        Character character
        String value
        String type
    }

    class DictionaryReference {
        long id
        Character character
        String value
        String type
        int morohashiVolume
        int morohashiPage
    }

    class QueryCode {
        long id
        Character character
        String value
        String type
        String skipMisclassification
    }

    class RMGroup {
        long id
        Character character
        Set<Reading> readings
        Set<Meaning> meanings
    }

    class Reading {
        long id
        RMGroup rmGroup
        String type
        String onType
        String rStatus
        String value
    }

    class Meaning {
        long id
        RMGroup rmGroup
        String languageCode
        String value
    }

    'Relationships
    Character <-down- Codepoint
    Character <-down- Radical
    Character <-down- Variant
    Character <-down- DictionaryReference
    Character <-down- QueryCode
    Character <-down- RMGroup
    RMGroup <-down- Reading
    RMGroup <-down- Meaning
}

@enduml