spring:
  application:
    name: jpapi
  datasource:
    url: jdbc:h2:./kg.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    open-in-view: true
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

file:
  sources:
    jmdict: src/main/resources/JMDict.xml
    jmnedict: src/main/resources/JMNEDict.xml
    kanjidic2: src/main/resources/Kanjidic2.xml
  furigana:
    jmdict: src/main/resources/JMDictFurigana.json
    jmnedict: src/main/resources/JMNEDictFurigana.json

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics