spring:
  application:
    name: kanjiguide-sp
  datasource:
    url: jdbc:h2:./kg.db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

file:
  jmdict: src/main/resources/JMDict-formatted.xml
  kanjidic2: src/main/resources/kanjidic2-formatted.xml

management:
  endpoints:
    web:
      exposure:
        include:
          - metrics

#logging:
#  level:
#    javax: info
#    sun: info
#    root: debug
