CREATE TABLE jmd_alt_reading
(
    id          BIGINT NOT NULL,
    alt_reading VARCHAR(255)
);

CREATE TABLE jmd_antonym
(
    id      BIGINT NOT NULL,
    antonym VARCHAR(255)
);

CREATE TABLE jmd_cross_ref
(
    id              BIGINT NOT NULL,
    cross_reference VARCHAR(255)
);

CREATE TABLE jmd_dialect
(
    id      BIGINT NOT NULL,
    dialect VARCHAR(255)
);

CREATE TABLE jmd_entry
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ent_seq BIGINT                                  NOT NULL,
    CONSTRAINT pk_jmd_entry PRIMARY KEY (id)
);

CREATE TABLE jmd_field_of_app
(
    id                   BIGINT NOT NULL,
    field_of_application VARCHAR(255)
);

CREATE TABLE jmd_gloss
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sense_id BIGINT                                  NOT NULL,
    element  VARCHAR(1000),
    lang     VARCHAR(255),
    g_gend   VARCHAR(255),
    g_type   VARCHAR(255),
    CONSTRAINT pk_jmd_gloss PRIMARY KEY (id)
);

CREATE TABLE jmd_kanji
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_id BIGINT                                  NOT NULL,
    element  VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_jmd_kanji PRIMARY KEY (id)
);

CREATE TABLE jmd_kanji_orth
(
    id                BIGINT NOT NULL,
    kanji_orthography VARCHAR(255)
);

CREATE TABLE jmd_kanji_pri
(
    id             BIGINT NOT NULL,
    kanji_priority VARCHAR(255)
);

CREATE TABLE jmd_kd2_assoc_char
(
    jmd_entry_id     BIGINT NOT NULL,
    kd2_character_id BIGINT NOT NULL,
    CONSTRAINT pk_jmd_kd2_assoc_char PRIMARY KEY (jmd_entry_id, kd2_character_id)
);

CREATE TABLE jmd_limit_kanji
(
    id               BIGINT NOT NULL,
    limited_to_kanji VARCHAR(255)
);

CREATE TABLE jmd_limit_read
(
    id                 BIGINT NOT NULL,
    limited_to_reading VARCHAR(255)
);

CREATE TABLE jmd_lsource
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sense_id                  BIGINT                                  NOT NULL,
    element                   VARCHAR(1000),
    language                  VARCHAR(255),
    semantic_coverage         VARCHAR(255),
    from_source_language_word BOOLEAN,
    CONSTRAINT pk_jmd_lsource PRIMARY KEY (id)
);

CREATE TABLE jmd_misc_info
(
    id        BIGINT NOT NULL,
    misc_info VARCHAR(255)
);

CREATE TABLE jmd_pos
(
    id             BIGINT NOT NULL,
    part_of_speech VARCHAR(255)
);

CREATE TABLE jmd_reading
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_id BIGINT                                  NOT NULL,
    element  VARCHAR(255)                            NOT NULL,
    nokanji  BOOLEAN,
    CONSTRAINT pk_jmd_reading PRIMARY KEY (id)
);

CREATE TABLE jmd_reading_info
(
    id           BIGINT NOT NULL,
    reading_info VARCHAR(255)
);

CREATE TABLE jmd_reading_pri
(
    id               BIGINT NOT NULL,
    reading_priority VARCHAR(255)
);

CREATE TABLE jmd_sense
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    entry_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_jmd_sense PRIMARY KEY (id)
);

CREATE TABLE jmd_sense_info
(
    id         BIGINT NOT NULL,
    sense_info VARCHAR(255)
);

CREATE TABLE kd2_character
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    literal      VARCHAR(255)                            NOT NULL,
    frequency    INT,
    school_grade INT,
    jlpt_grade   INT,
    stroke_count INT                                     NOT NULL,
    CONSTRAINT pk_kd2_character PRIMARY KEY (id)
);

CREATE TABLE kd2_codepoint
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element      VARCHAR(255),
    type         VARCHAR(255),
    character_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_kd2_codepoint PRIMARY KEY (id)
);

CREATE TABLE kd2_dic_ref
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element      VARCHAR(255),
    type         VARCHAR(255),
    character_id BIGINT                                  NOT NULL,
    m_vol        INT,
    m_page       INT,
    CONSTRAINT pk_kd2_dic_ref PRIMARY KEY (id)
);

CREATE TABLE kd2_meaning
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rmgroup_id BIGINT                                  NOT NULL,
    lang       VARCHAR(255),
    element    VARCHAR(255),
    CONSTRAINT pk_kd2_meaning PRIMARY KEY (id)
);

CREATE TABLE kd2_nanori
(
    id     BIGINT NOT NULL,
    nanori VARCHAR(255)
);

CREATE TABLE kd2_qcode
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element       VARCHAR(255),
    type          VARCHAR(255),
    character_id  BIGINT                                  NOT NULL,
    skip_misclass VARCHAR(255),
    CONSTRAINT pk_kd2_qcode PRIMARY KEY (id)
);

CREATE TABLE kd2_radical
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element      VARCHAR(255),
    type         VARCHAR(255),
    character_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_kd2_radical PRIMARY KEY (id)
);

CREATE TABLE kd2_radnames
(
    id       BIGINT NOT NULL,
    radnames VARCHAR(255)
);

CREATE TABLE kd2_reading
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element    VARCHAR(255),
    type       VARCHAR(255),
    rmgroup_id BIGINT                                  NOT NULL,
    on_type    VARCHAR(255),
    r_status   VARCHAR(255),
    CONSTRAINT pk_kd2_reading PRIMARY KEY (id)
);

CREATE TABLE kd2_rmgroup
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    character_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_kd2_rmgroup PRIMARY KEY (id)
);

CREATE TABLE kd2_variant
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    element      VARCHAR(255),
    type         VARCHAR(255),
    character_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_kd2_variant PRIMARY KEY (id)
);

ALTER TABLE jmd_entry
    ADD CONSTRAINT uc_jmd_entry_ent_seq UNIQUE (ent_seq);

ALTER TABLE kd2_character
    ADD CONSTRAINT uc_kd2_character_literal UNIQUE (literal);

CREATE INDEX idx_219f9a80d1186962083e9fef0 ON jmd_gloss (element);

CREATE INDEX idx_5450136e22f2ecc4177a2579a ON jmd_reading (element);

CREATE INDEX idx_da92c9603d6648516d92ce5bf ON jmd_kanji (element);

ALTER TABLE jmd_gloss
    ADD CONSTRAINT FK_JMD_GLOSS_ON_SENSE FOREIGN KEY (sense_id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_kanji
    ADD CONSTRAINT FK_JMD_KANJI_ON_ENTRY FOREIGN KEY (entry_id) REFERENCES jmd_entry (id);

ALTER TABLE jmd_lsource
    ADD CONSTRAINT FK_JMD_LSOURCE_ON_SENSE FOREIGN KEY (sense_id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_reading
    ADD CONSTRAINT FK_JMD_READING_ON_ENTRY FOREIGN KEY (entry_id) REFERENCES jmd_entry (id);

ALTER TABLE jmd_sense
    ADD CONSTRAINT FK_JMD_SENSE_ON_ENTRY FOREIGN KEY (entry_id) REFERENCES jmd_entry (id);

ALTER TABLE kd2_codepoint
    ADD CONSTRAINT FK_KD2_CODEPOINT_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE kd2_dic_ref
    ADD CONSTRAINT FK_KD2_DIC_REF_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE kd2_meaning
    ADD CONSTRAINT FK_KD2_MEANING_ON_RMGROUP FOREIGN KEY (rmgroup_id) REFERENCES kd2_rmgroup (id);

ALTER TABLE kd2_qcode
    ADD CONSTRAINT FK_KD2_QCODE_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE kd2_radical
    ADD CONSTRAINT FK_KD2_RADICAL_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE kd2_reading
    ADD CONSTRAINT FK_KD2_READING_ON_RMGROUP FOREIGN KEY (rmgroup_id) REFERENCES kd2_rmgroup (id);

ALTER TABLE kd2_rmgroup
    ADD CONSTRAINT FK_KD2_RMGROUP_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE kd2_variant
    ADD CONSTRAINT FK_KD2_VARIANT_ON_CHARACTER FOREIGN KEY (character_id) REFERENCES kd2_character (id);

ALTER TABLE jmd_alt_reading
    ADD CONSTRAINT fk_jmd_alt_reading_on_j_reading FOREIGN KEY (id) REFERENCES jmd_reading (id);

ALTER TABLE jmd_antonym
    ADD CONSTRAINT fk_jmd_antonym_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_cross_ref
    ADD CONSTRAINT fk_jmd_cross_ref_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_dialect
    ADD CONSTRAINT fk_jmd_dialect_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_field_of_app
    ADD CONSTRAINT fk_jmd_field_of_app_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_kanji_orth
    ADD CONSTRAINT fk_jmd_kanji_orth_on_kanji FOREIGN KEY (id) REFERENCES jmd_kanji (id);

ALTER TABLE jmd_kanji_pri
    ADD CONSTRAINT fk_jmd_kanji_pri_on_kanji FOREIGN KEY (id) REFERENCES jmd_kanji (id);

ALTER TABLE jmd_limit_kanji
    ADD CONSTRAINT fk_jmd_limit_kanji_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_limit_read
    ADD CONSTRAINT fk_jmd_limit_read_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_misc_info
    ADD CONSTRAINT fk_jmd_misc_info_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_pos
    ADD CONSTRAINT fk_jmd_pos_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_reading_info
    ADD CONSTRAINT fk_jmd_reading_info_on_j_reading FOREIGN KEY (id) REFERENCES jmd_reading (id);

ALTER TABLE jmd_reading_pri
    ADD CONSTRAINT fk_jmd_reading_pri_on_j_reading FOREIGN KEY (id) REFERENCES jmd_reading (id);

ALTER TABLE jmd_sense_info
    ADD CONSTRAINT fk_jmd_sense_info_on_sense FOREIGN KEY (id) REFERENCES jmd_sense (id);

ALTER TABLE jmd_kd2_assoc_char
    ADD CONSTRAINT fk_jmdkd2asscha_on_character FOREIGN KEY (kd2_character_id) REFERENCES kd2_character (id);

ALTER TABLE jmd_kd2_assoc_char
    ADD CONSTRAINT fk_jmdkd2asscha_on_entry FOREIGN KEY (jmd_entry_id) REFERENCES jmd_entry (id);

ALTER TABLE kd2_nanori
    ADD CONSTRAINT fk_kd2_nanori_on_character FOREIGN KEY (id) REFERENCES kd2_character (id);

ALTER TABLE kd2_radnames
    ADD CONSTRAINT fk_kd2_radnames_on_character FOREIGN KEY (id) REFERENCES kd2_character (id);