-- ###################################################################################################
-- ############################################# JMDict ##############################################
-- ###################################################################################################

-- ############################################# Tables ##############################################

-- JMDictEntry
CREATE TABLE jmd_entry
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    ent_seq                             BIGINT                                          NOT NULL,
    CONSTRAINT pk_jmd_entry             PRIMARY KEY (id)
);

-- JMDictEntry#linkedCharacters (Many-to-many)
CREATE TABLE jmd_kd2_assoc_char
(
    jmd_entry_id                        BIGINT                                          NOT NULL,
    kd2_character_id                    BIGINT                                          NOT NULL,
    CONSTRAINT pk_jmd_kd2_assoc_char    PRIMARY KEY (jmd_entry_id, kd2_character_id)
);

-- JMDictKanji
CREATE TABLE jmd_kanji
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    CONSTRAINT pk_jmd_kanji             PRIMARY KEY (id)
);

-- JMDictKanji#orthographyInformation (ElementCollection)
CREATE TABLE jmd_kanji_orth
(
    id                                  BIGINT                                          NOT NULL,
    kanji_orthography                   VARCHAR(255)
);

-- JMDictKanji#priorityInformation (ElementCollection)
CREATE TABLE jmd_kanji_pri
(
    id                                  BIGINT                                          NOT NULL,
    kanji_priority                      VARCHAR(255)
);

-- JMDictReading
CREATE TABLE jmd_reading
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    nokanji                             BOOLEAN,
    CONSTRAINT pk_jmd_reading           PRIMARY KEY (id)
);

-- JMDictReading#readingInformation (ElementCollection)
CREATE TABLE jmd_reading_info
(
    id                                  BIGINT                                          NOT NULL,
    reading_info                        VARCHAR(255)
);

-- JMDictReading#priorityInformation (ElementCollection)
CREATE TABLE jmd_reading_pri
(
    id                                  BIGINT                                          NOT NULL,
    reading_priority                    VARCHAR(255)
);

-- JMDictReading#alternativeReadings (ElementCollection)
CREATE TABLE jmd_alt_reading
(
    id                                  BIGINT                                          NOT NULL,
    alt_reading                         VARCHAR(255)
);

-- JMDictReadingFurigana
CREATE TABLE jmd_reading_fg
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    reading_id                          BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    kana                                VARCHAR(255),
    pos                                 INT                                             NOT NULL
);

-- JMDictSense
CREATE TABLE jmd_sense
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    CONSTRAINT pk_jmd_sense             PRIMARY KEY (id)
);

-- JMDictSense#limitedToKanji (ElementCollection)
CREATE TABLE jmd_limit_kanji
(
    id                                  BIGINT                                          NOT NULL,
    limited_to_kanji                    VARCHAR(255)
);

-- JMDictSense#limitedToReadings (ElementCollection)
CREATE TABLE jmd_limit_read
(
    id                                  BIGINT                                          NOT NULL,
    limited_to_reading                  VARCHAR(255)
);

-- JMDictSense#partOfSpeech (ElementCollection)
CREATE TABLE jmd_pos
(
    id                                  BIGINT                                          NOT NULL,
    part_of_speech                      VARCHAR(255)
);

-- JMDictSense#crossReferences (ElementCollection)
CREATE TABLE jmd_cross_ref
(
    id                                  BIGINT                                          NOT NULL,
    cross_reference                     VARCHAR(255)
);

-- JMDictSense#antonyms (ElementCollection)
CREATE TABLE jmd_antonym
(
    id                                  BIGINT                                          NOT NULL,
    antonym                             VARCHAR(255)
);

-- JMDictSense#fieldsOfApplication (ElementCollection)
CREATE TABLE jmd_field_of_app
(
    id                                  BIGINT                                          NOT NULL,
    field_of_application                VARCHAR(255)
);

-- JMDictSense#miscellaneousInformation (ElementCollection)
CREATE TABLE jmd_misc_info
(
    id                                  BIGINT                                          NOT NULL,
    misc_info                           VARCHAR(255)
);

-- JMDictSense#senseInformation (ElementCollection)
CREATE TABLE jmd_sense_info
(
    id                                  BIGINT                                          NOT NULL,
    sense_info                          VARCHAR(255)
);

-- JMDictSense#dialects (ElementCollection)
CREATE TABLE jmd_dialect
(
    id                                  BIGINT                                          NOT NULL,
    dialect                             VARCHAR(255)
);

-- JMDictGloss
CREATE TABLE jmd_gloss
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    sense_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(1000),
    lang                                VARCHAR(255),
    g_gend                              VARCHAR(255),
    g_type                              VARCHAR(255),
    CONSTRAINT pk_jmd_gloss             PRIMARY KEY (id)
);

-- JMDictLoanwordSource
CREATE TABLE jmd_lsource
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    sense_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(1000),
    lang                                VARCHAR(255),
    semantic_coverage                   VARCHAR(255),
    from_source_lang_word               BOOLEAN,
    CONSTRAINT pk_jmd_lsource           PRIMARY KEY (id)
);

-- ####################################### Unique constraints ########################################

-- JMDictEntry (ID)
ALTER TABLE jmd_entry
    ADD CONSTRAINT uc_jmd_entry_ent_seq
        UNIQUE (ent_seq);

-- ##################################### Foreign key constraints #####################################

-- JMDictKanji > JMDictEntry
ALTER TABLE jmd_kanji
    ADD CONSTRAINT fk_jmd_kanji_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmd_entry (id);

-- JMDictKanji#orthographyInformation > JMDictKanji
ALTER TABLE jmd_kanji_orth
    ADD CONSTRAINT fk_jmd_kanji_orth_on_kanji
        FOREIGN KEY (id)
            REFERENCES jmd_kanji (id);

-- JMDictKanji#priorityInformation > JMDictKanji
ALTER TABLE jmd_kanji_pri
    ADD CONSTRAINT fk_jmd_kanji_pri_on_kanji
        FOREIGN KEY (id)
            REFERENCES jmd_kanji (id);

-- JMDictReading > JMDictEntry
ALTER TABLE jmd_reading
    ADD CONSTRAINT fk_jmd_reading_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmd_entry (id);

-- JMDictReading#readingInformation > JMDictReading
ALTER TABLE jmd_reading_info
    ADD CONSTRAINT fk_jmd_reading_info_on_reading
        FOREIGN KEY (id)
            REFERENCES jmd_reading (id);

-- JMDictReading#priorityInformation > JMDictReading
ALTER TABLE jmd_reading_pri
    ADD CONSTRAINT fk_jmd_reading_pri_on_reading
        FOREIGN KEY (id)
            REFERENCES jmd_reading (id);

-- JMDictReading#alternativeReadings > JMDictReading
ALTER TABLE jmd_alt_reading
    ADD CONSTRAINT fk_jmd_alt_reading_on_reading
        FOREIGN KEY (id)
            REFERENCES jmd_reading (id);

-- JMDictReadingFurigana > JMDictReading
ALTER TABLE jmd_reading_fg
    ADD CONSTRAINT fk_jmd_reading_fg_on_reading
        FOREIGN KEY (reading_id)
            REFERENCES jmd_reading (id);

-- JMDictSense > JMDictEntry
ALTER TABLE jmd_sense
    ADD CONSTRAINT fk_jmd_sense_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmd_entry (id);

-- JMDictSense#limitedToKanji > JMDictSense
ALTER TABLE jmd_limit_kanji
    ADD CONSTRAINT fk_jmd_limit_kanji_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#limitedToReadings > JMDictSense
ALTER TABLE jmd_limit_read
    ADD CONSTRAINT fk_jmd_limit_read_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#partOfSpeech > JMDictSense
ALTER TABLE jmd_pos
    ADD CONSTRAINT fk_jmd_pos_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#crossReferences > JMDictSense
ALTER TABLE jmd_cross_ref
    ADD CONSTRAINT fk_jmd_cross_ref_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#antonyms > JMDictSense
ALTER TABLE jmd_antonym
    ADD CONSTRAINT fk_jmd_antonym_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#fieldsOfApplication > JMDictSense
ALTER TABLE jmd_field_of_app
    ADD CONSTRAINT fk_jmd_field_of_app_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#miscellaneousInformation > JMDictSense
ALTER TABLE jmd_misc_info
    ADD CONSTRAINT fk_jmd_misc_info_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#senseInformation
ALTER TABLE jmd_sense_info
    ADD CONSTRAINT fk_jmd_sense_info_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictSense#dialects > JMDictSense
ALTER TABLE jmd_dialect
    ADD CONSTRAINT fk_jmd_dialect_on_sense
        FOREIGN KEY (id)
            REFERENCES jmd_sense (id);

-- JMDictGloss > JMDictSense
ALTER TABLE jmd_gloss
    ADD CONSTRAINT fk_jmd_gloss_on_entry
        FOREIGN KEY (sense_id)
            REFERENCES jmd_sense (id);

-- JMDictLoanwordSource > JMDictSense
ALTER TABLE jmd_lsource
    ADD CONSTRAINT fk_jmd_lsource_on_entry
        FOREIGN KEY (sense_id)
            REFERENCES jmd_sense (id);

-- ############################################# Indexes #############################################

-- JMDictKanji#element
CREATE INDEX idx_jmd_kanji_element
    ON jmd_kanji (element);

-- JMDictReading#element
CREATE INDEX idx_jmd_reading_element
    ON jmd_reading (element);

-- JMDictGloss#element
CREATE INDEX idx_jmd_gloss_element
    ON jmd_gloss (element);

-- ###################################################################################################
-- ########################################### Kanjidic2 #############################################
-- ###################################################################################################

-- ############################################# Tables ##############################################

-- Kanjidic2Character
CREATE TABLE kd2_character
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    literal                             VARCHAR(255)                                    NOT NULL,
    frequency                           INT,
    school_grade                        INT,
    jlpt_grade                          INT,
    stroke_count                        INT                                             NOT NULL,
    CONSTRAINT pk_kd2_character         PRIMARY KEY (id)
);

-- Kanjidic2Character#radicalNames (Many-to-many)
CREATE TABLE kd2_radnames
(
    id                                  BIGINT                                          NOT NULL,
    radnames                            VARCHAR(255)
);

-- Kanjidic2Character#nanori (Many-to-many)
CREATE TABLE kd2_nanori
(
    id                                  BIGINT                                          NOT NULL,
    nanori                              VARCHAR(255)
);

-- Kanjidic2Codepoint
CREATE TABLE kd2_codepoint
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    character_id                        BIGINT                                          NOT NULL,
    CONSTRAINT pk_kd2_codepoint         PRIMARY KEY (id)
);

-- Kanjidic2Radical
CREATE TABLE kd2_radical
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    character_id                        BIGINT                                          NOT NULL,
    CONSTRAINT pk_kd2_radical           PRIMARY KEY (id)
);

-- Kanjidic2Variant
CREATE TABLE kd2_variant
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    character_id                        BIGINT                                          NOT NULL,
    CONSTRAINT pk_kd2_variant           PRIMARY KEY (id)
);

-- Kanjidic2DictionaryReference
CREATE TABLE kd2_dic_ref
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    character_id                        BIGINT                                          NOT NULL,
    m_vol                               INT,
    m_page                              INT,
    CONSTRAINT pk_kd2_dic_ref           PRIMARY KEY (id)
);

-- Kanjidic2QueryCode
CREATE TABLE kd2_qcode
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    character_id                        BIGINT                                          NOT NULL,
    skip_misclass                       VARCHAR(255),
    CONSTRAINT pk_kd2_qcode             PRIMARY KEY (id)
);

-- Kanjidic2SemanticGroup
CREATE TABLE kd2_semgroup
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    character_id                        BIGINT                                          NOT NULL,
    CONSTRAINT pk_kd2_semgroup          PRIMARY KEY (id)
);

-- Kanjidic2Meaning
CREATE TABLE kd2_meaning
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    semgroup_id                         BIGINT                                          NOT NULL,
    lang                                VARCHAR(255),
    element                             VARCHAR(255),
    CONSTRAINT pk_kd2_meaning           PRIMARY KEY (id)
);

-- Kanjidic2Reading
CREATE TABLE kd2_reading
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    element                             VARCHAR(255),
    type                                VARCHAR(255),
    semgroup_id                         BIGINT                                          NOT NULL,
    on_type                             VARCHAR(255),
    r_status                            VARCHAR(255),
    CONSTRAINT pk_kd2_reading           PRIMARY KEY (id)
);

-- ####################################### Unique constraints ########################################

-- Kanjidic2Character (ID)
ALTER TABLE kd2_character
    ADD CONSTRAINT uc_kd2_character_literal
        UNIQUE (literal);

-- ##################################### Foreign key constraints #####################################

-- JMDictEntry > Kanjidic2Character
ALTER TABLE jmd_kd2_assoc_char
    ADD CONSTRAINT fk_jmdkd2asscha_on_character
        FOREIGN KEY (kd2_character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2Character > JMDictEntry
ALTER TABLE jmd_kd2_assoc_char
    ADD CONSTRAINT fk_jmdkd2asscha_on_jmd_entry
        FOREIGN KEY (jmd_entry_id)
            REFERENCES jmd_entry (id);

-- Kanjidic2Character#radicalNames > Kanjidic2Character
ALTER TABLE kd2_radnames
    ADD CONSTRAINT fk_kd2_radnames_on_character
        FOREIGN KEY (id)
            REFERENCES kd2_character (id);

-- Kanjidic2Character#nanori > Kanjidic2Character
ALTER TABLE kd2_nanori
    ADD CONSTRAINT fk_kd2_nanori_on_character
        FOREIGN KEY (id)
            REFERENCES kd2_character (id);

-- Kanjidic2Codepoint > Kanjidic2Character
ALTER TABLE kd2_codepoint
    ADD CONSTRAINT fk_kd2_codepoint_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2Radical > Kanjidic2Character
ALTER TABLE kd2_radical
    ADD CONSTRAINT fk_kd2_radical_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2Variant > Kanjidic2Character
ALTER TABLE kd2_variant
    ADD CONSTRAINT fk_kd2_variant_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2DictionaryReference > Kanjidic2Character
ALTER TABLE kd2_dic_ref
    ADD CONSTRAINT fk_kd2_dic_ref_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2QueryCode > Kanjidic2Character
ALTER TABLE kd2_qcode
    ADD CONSTRAINT fk_kd2_qcode_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2SemanticGroup > Kanjidic2Character
ALTER TABLE kd2_semgroup
    ADD CONSTRAINT fk_kd2_semgroup_on_character
        FOREIGN KEY (character_id)
            REFERENCES kd2_character (id);

-- Kanjidic2Reading > Kanjidic2SemanticGroup
ALTER TABLE kd2_reading
    ADD CONSTRAINT fk_kd2_reading_on_character
        FOREIGN KEY (semgroup_id)
            REFERENCES kd2_semgroup (id);

-- Kanjidic2Meaning > Kanjidic2SemanticGroup
ALTER TABLE kd2_meaning
    ADD CONSTRAINT fk_kd2_meaning_on_character
        FOREIGN KEY (semgroup_id)
            REFERENCES kd2_semgroup (id);

-- ###################################################################################################
--  ########################################### JMNEdict  ############################################
-- ###################################################################################################

-- ############################################# Tables ##############################################

-- JMNEDictEntry
CREATE TABLE jmned_entry
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    CONSTRAINT pk_jmned_entry           PRIMARY KEY (id)
);

-- JMNEDictEntry#linkedCharacters (Many-to-many)
CREATE TABLE jmned_kd2_assoc_char
(
    jmned_entry_id                      BIGINT                                          NOT NULL,
    kd2_character_id                    BIGINT                                          NOT NULL,
    CONSTRAINT pk_jmned_kd2_assoc_char  PRIMARY KEY (jmned_entry_id, kd2_character_id)
);

-- JMNEDictKanji
CREATE TABLE jmned_kanji
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    CONSTRAINT pk_jmned_kanji           PRIMARY KEY (id)
);

-- JMNEDictKanji#orthographyInformation (ElementCollection)
CREATE TABLE jmned_kanji_orth
(
    id                                  BIGINT                                          NOT NULL,
    kanji_orthography                   VARCHAR(255)
);

-- JMNEDictKanji#priorityInformation (ElementCollection)
CREATE TABLE jmned_kanji_pri
(
    id                                  BIGINT                                          NOT NULL,
    kanji_priority                      VARCHAR(255)
);

-- JMNEDictReading
CREATE TABLE jmned_reading
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    CONSTRAINT pk_jmned_reading         PRIMARY KEY (id)
);

-- JMNEDictReading#readingInformation (ElementCollection)
CREATE TABLE jmned_reading_info
(
    id                                  BIGINT                                          NOT NULL,
    reading_info                        VARCHAR(255)
);

-- JMNEDictReading#priorityInformation (ElementCollection)
CREATE TABLE jmned_reading_pri
(
    id                                  BIGINT                                          NOT NULL,
    reading_priority                    VARCHAR(255)
);

-- JMNEDictReading#alternativeReadings (ElementCollection)
CREATE TABLE jmned_alt_reading
(
    id                                  BIGINT                                          NOT NULL,
    alt_reading                         VARCHAR(255)
);

-- JMNEDictReadingFurigana
CREATE TABLE jmned_reading_fg
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    reading_id                          BIGINT                                          NOT NULL,
    element                             VARCHAR(255)                                    NOT NULL,
    kana                                VARCHAR(255),
    pos                                 INT                                             NOT NULL
);

-- JMNEDictTranslation
CREATE TABLE jmned_trans
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    entry_id                            BIGINT                                          NOT NULL,
    CONSTRAINT pk_jmned_trans           PRIMARY KEY (id)
);

-- JMNEDictTranslation#translationTypes (ElementCollection)
CREATE TABLE jmned_trans_type
(
    id                                  BIGINT                                          NOT NULL,
    trans_type                          VARCHAR(255)
);

-- JMNEDictTranslationDetail
CREATE TABLE jmned_trans_detail
(
    id                                  BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL,
    trans_id                            BIGINT                                          NOT NULL,
    trans_name                          VARCHAR(255),
    lang                                VARCHAR(255),
    CONSTRAINT pk_jmned_trans_detail    PRIMARY KEY (id)
);

-- ##################################### Foreign key constraints #####################################

-- Kanjidic2Character > JMNEDictEntry
ALTER TABLE jmned_kd2_assoc_char
    ADD CONSTRAINT fk_jmnkd2asscha_on_jmned_entry
        FOREIGN KEY (jmned_entry_id)
            REFERENCES jmned_entry (id);

-- JMNEDictKanji > JMNEDictEntry
ALTER TABLE jmned_kanji
    ADD CONSTRAINT fk_jmned_kanji_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmned_entry (id);

-- JMNEDictKanji#orthographyInformation > JMNEDictKanji
ALTER TABLE jmned_kanji_orth
    ADD CONSTRAINT fk_jmned_kanji_orth_on_kanji
        FOREIGN KEY (id)
            REFERENCES jmned_kanji (id);

-- JMNEDictKanji#priorityInformation > JMNEDictKanji
ALTER TABLE jmned_kanji_pri
    ADD CONSTRAINT fk_jmned_kanji_pri_on_kanji
        FOREIGN KEY (id)
            REFERENCES jmned_kanji (id);

-- JMNEDictReading > JMNEDictEntry
ALTER TABLE jmned_reading
    ADD CONSTRAINT fk_jmned_reading_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmned_entry (id);

-- JMNEDictReading#readingInformation > JMNEDictReading
ALTER TABLE jmned_reading_info
    ADD CONSTRAINT fk_jmned_reading_info_on_reading
        FOREIGN KEY (id)
            REFERENCES jmned_reading (id);

-- JMNEDictReading#priorityInformation > JMNEDictReading
ALTER TABLE jmned_reading_pri
    ADD CONSTRAINT fk_jmned_reading_pri_on_reading
        FOREIGN KEY (id)
            REFERENCES jmned_reading (id);

-- JMNEDictReading#alternativeReadings > JMDictReading
ALTER TABLE jmned_alt_reading
    ADD CONSTRAINT fk_jmned_alt_reading_on_reading
        FOREIGN KEY (id)
            REFERENCES jmned_reading (id);

-- JMDictReadingFurigana > JMDictReading
ALTER TABLE jmned_reading_fg
    ADD CONSTRAINT fk_jmned_reading_fg_on_reading
        FOREIGN KEY (reading_id)
            REFERENCES jmned_reading (id);

-- JMNEDictTranslation > JMNEDictEntry
ALTER TABLE jmned_trans
    ADD CONSTRAINT fk_jmned_trans_on_entry
        FOREIGN KEY (entry_id)
            REFERENCES jmned_entry (id);

-- JMNEDictTranslation#translationTypes > JMNEDictTranslation
ALTER TABLE jmned_trans_type
    ADD CONSTRAINT fk_jmned_trans_type_on_translation
        FOREIGN KEY (id)
            REFERENCES jmned_trans (id);

-- JMNEDictTranslationDetail > JMNEDictTranslation
ALTER TABLE jmned_trans_detail
    ADD CONSTRAINT fk_jmned_trans_detail_on_translation
        FOREIGN KEY (trans_id)
            REFERENCES jmned_trans (id);

-- JMNEDictEntry > Kanjidic2Character
ALTER TABLE jmned_kd2_assoc_char
    ADD CONSTRAINT fk_jmnkd2asscha_on_character
        FOREIGN KEY (kd2_character_id)
            REFERENCES kd2_character (id);